/// Integration test: reads test_cases.json generated by the TypeScript tool
/// and verifies that the Rust `decrypt_record` produces the same outputs.

use serde::Deserialize;
use std::path::PathBuf;
use tls_decrypt_rs::{decrypt_record, Direction, KeyDerivationParams, RawRecord};

#[derive(Debug, Deserialize)]
struct TestCase {
    name: String,
    params: TestParams,
    records: Vec<TestRecord>,
}

#[derive(Debug, Deserialize)]
struct TestParams {
    #[serde(rename = "capturedPrivKeys")]
    captured_priv_keys: std::collections::HashMap<String, String>, // alg -> hex
    #[serde(rename = "negotiatedCipherSuite")]
    negotiated_cipher_suite: String,
    #[serde(rename = "handshakeMsgs")]
    handshake_msgs: Vec<String>, // hex
}

#[derive(Debug, Deserialize)]
struct TestRecord {
    ciphertext: String, // hex
    #[serde(rename = "recordNumber")]
    record_number: u32,
    direction: String, // "ServerToClient" | "ClientToServer"
    expected: Expected,
}

#[derive(Debug, Deserialize)]
struct Expected {
    #[serde(rename = "plaintextHex")]
    plaintext_hex: String,
    algorithm: String,
    #[serde(rename = "nonceHex")]
    nonce_hex: String,
}

fn load_test_cases() -> TestCase {
    // Try multiple paths — cargo runs from the crate root
    let candidates = [
        PathBuf::from("../../test/test_cases.json"),
        PathBuf::from("../test/test_cases.json"),
        PathBuf::from("tls/test/test_cases.json"),
    ];

    for p in &candidates {
        if p.exists() {
            let data = std::fs::read_to_string(p).unwrap();
            return serde_json::from_str(&data).unwrap();
        }
    }

    panic!(
        "test_cases.json not found. Run: npx tsx test/generate-test-cases.ts"
    );
}

#[test]
fn decrypt_record_from_typescript_vectors() {
    let tc = load_test_cases();
    eprintln!("\n  🧪 Rust test: {}", tc.name);
    eprintln!("  Cipher: {}", tc.params.negotiated_cipher_suite);
    eprintln!("  Handshake msgs: {}", tc.params.handshake_msgs.len());
    eprintln!("  Records: {}\n", tc.records.len());

    // Build KeyDerivationParams
    let captured_priv_keys: Vec<(String, Vec<u8>)> = tc
        .params
        .captured_priv_keys
        .iter()
        .map(|(alg, h)| (alg.clone(), hex::decode(h).unwrap()))
        .collect();

    let handshake_msgs: Vec<Vec<u8>> = tc
        .params
        .handshake_msgs
        .iter()
        .map(|h| hex::decode(h).unwrap())
        .collect();

    let params = KeyDerivationParams {
        captured_priv_keys,
        negotiated_cipher_suite: tc.params.negotiated_cipher_suite.clone(),
        handshake_msgs,
    };

    let mut passed = 0;
    let mut failed = 0;

    for (i, tr) in tc.records.iter().enumerate() {
        let rec = RawRecord {
            ciphertext: hex::decode(&tr.ciphertext).unwrap(),
            record_number: tr.record_number,
            direction: match tr.direction.as_str() {
                "ServerToClient" => Direction::ServerToClient,
                "ClientToServer" => Direction::ClientToServer,
                _ => panic!("Unknown direction: {}", tr.direction),
            },
        };

        let result = decrypt_record(&rec, &params);

        match result {
            Ok(result) => {
                let pt_hex = hex::encode(&result.plaintext);
                let nonce_hex = hex::encode(&result.nonce);
                let pt_ok = pt_hex == tr.expected.plaintext_hex;
                let algo_ok = result.algorithm == tr.expected.algorithm;
                let nonce_ok = nonce_hex == tr.expected.nonce_hex;

                if pt_ok && algo_ok && nonce_ok {
                    eprintln!(
                        "  ✅ Record {} ({}): {} — {}…",
                        i,
                        tr.direction,
                        result.algorithm,
                        &tr.expected.plaintext_hex[..32.min(tr.expected.plaintext_hex.len())]
                    );
                    passed += 1;
                } else {
                    eprintln!("  ❌ Record {} ({}): MISMATCH", i, tr.direction);
                    if !pt_ok {
                        eprintln!(
                            "     plaintext: got {}… expected {}…",
                            &pt_hex[..32.min(pt_hex.len())],
                            &tr.expected.plaintext_hex[..32.min(tr.expected.plaintext_hex.len())]
                        );
                    }
                    if !algo_ok {
                        eprintln!(
                            "     algorithm: got {} expected {}",
                            result.algorithm, tr.expected.algorithm
                        );
                    }
                    if !nonce_ok {
                        eprintln!("     nonce: got {} expected {}", nonce_hex, tr.expected.nonce_hex);
                    }
                    failed += 1;
                }
            }
            Err(e) => {
                eprintln!("  ❌ Record {} ({}): Error: {}", i, tr.direction, e);
                failed += 1;
            }
        }
    }

    eprintln!("\n  {} passed, {} failed", passed, failed);
    assert_eq!(failed, 0, "{} record(s) failed", failed);
}
